#!/bin/bash 
# Usage: psort filename <chunksize> <threads>
# In this example a the file largefile is split into chunks of 1000 lines
# The part are sorted in 4 simultaneous threads before getting merged.
# 
# psort largefile.txt 10000 4    
#
# by h.p.
split -l $2 $1 $1.part
suffix=sorttemp.`date +%s`
nthreads=$3
i=0

for fname in `ls $1.part*`
do
    let i++
    sort $fname > $fname.$suffix &
    mres=$(($i % $nthreads))
    test "$mres" -eq 0 && wait
done
wait

sort -m $(dirname $1)/*.$suffix

rm $1.part*
