#!/bin/sh

REPORT=pace-stats/times.csv

run() {
    play -Dpace.reportFile=$REPORT "$@" test
}

CORES=24

# rm $REPORT
# for s in 100000 1000000 4000000 10000000; do

#     for w in 10 100 200 400 1000; do
#         run -Dpace.cores=$CORES -Dpace.windowSize=$w -Dpace.limit=$s 
#     done

# done

REPORT=pace-stats/cores.csv

#rm $REPORT
#for c in 4 6 8 10 14 18 24; do
#    run -Dpace.cores=$c -Dpace.windowSize=100
#done


REPORT=pace-stats/simhash.csv

rm -f $REPORT
for s in 8 4 2 1; do
    run -Dpace.algo=simhash -Dpace.simhashRotationStep=$s -Dpace.windowSize=100
done


#REPORT=pace-stats/ngram.csv

#rm -f $REPORT
#for s in 2 3 4 5; do
#    run -Dpace.algo=ngram -Dpace.ngramSize=$s -Dpace.windowSize=10
#done
