#!/bin/sh

REPORT=pace-stats/times.csv

run() {
    play -Dpace.reportFile=$REPORT "$@" test
}

CORES=24

rm $REPORT
for s in 100000 1000000 4000000 10000000; do

    for w in 10 100 200 400 1000; do
        run -Dpace.cores=$CORES -Dpace.windowSize=$w -Dpace.limit=$s 
    done

done
